#
#
baseurl = "https://s-brigade.github.io/"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "ja-JP"
layoutdir = "layouts"
publishdir = "public"
author = "S-Brigade"
title = "Web Site"
disqusshortname = ""
pluralizelisttitles = false

googleanalytics="UA-116146829-1"

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "S-Brigade Web Site"
copyright = "Copyright © 2018 S-Brigade"
copyrightUrl = "/"
logofile = "img/logo.png"
faviconfile = "img/fav.png"
highlightjs = true
progressively = true
#share = true
latestpostcount = 5
#github = "example"
#email = "you@example.com"
#linkedin = "john-example-aa80ue8è"
#twitter = "example"
#facebook = "facebook_id"
#social_banner = "img/banner.png"
#usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName/tree/master"
small_banner_logo = false

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"